### PR TITLE
readme: update location of the firmware selector project

### PR DESCRIPTION
**Pull request by Lanchon**
The firmware selector project moved to GitHub.

### CODE REVIEW

**Comment by Lanchon** [comment]
i just noticed that my signed off by used my alias (Lanchon) instead of my name. maintainers: i release this trivial change to the public domain. feel free to reuse this change and sign it off yourself.

**Comment by Lanchon** [comment]
@aparcar

**Comment by aparcar** [comment]
I can't see the change anymore since you closed it. Can you please reopen it with your preferred signature?

**Comment by Lanchon** [comment]
hi @aparcar 

that's strange, i can still see it here: https://github.com/openwrt/asu/pull/895/commits/e6642580dd10bd6f4f86f3f9b3b32f0da5657f64

anyway, this was the change:
```diff
diff --git a/README.md b/README.md
index 01c68088..6a49a387 100644
--- a/README.md
+++ b/README.md
@@ -21,7 +21,7 @@ Simple web interface using vanilla JavaScript currently developed by @mwarning.
 It offers a device search based on model names and show links either to
 [official images](https://downloads.openwrt.org/) or requests images via the
 _asu_ API. Please join in the development at
-[GitLab repository](https://gitlab.com/openwrt/web/firmware-selector-openwrt-org)
+[GitHub repository](https://github.com/openwrt/firmware-selector-openwrt-org).
 
 * <https://firmware-selector.openwrt.org>
 
```

i'm sorry i made the change directly on github (on which i don't want my name). i won't be on my PC for a while. anyway it's not really important.

many thanks for ASU !!!

**Pull request closed without merging**
